/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbTestDialog: typeof import('./src/components/ab/AbTestDialog.vue')['default']
    AgentSelector: typeof import('./src/components/AgentSelector.vue')['default']
    AttachmentPreview: typeof import('./src/components/common/AttachmentPreview.vue')['default']
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    CodeBlock: typeof import('./src/components/common/CodeBlock.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    JSONViewer: typeof import('./src/components/common/JSONViewer.vue')['default']
    KnowledgeFloating: typeof import('./src/components/KnowledgeFloating.vue')['default']
    LanguageSelector: typeof import('./src/components/common/LanguageSelector.vue')['default']
    MessageActions: typeof import('./src/components/common/MessageActions.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    Notification: typeof import('./src/components/common/Notification.vue')['default']
    NotificationContainer: typeof import('./src/components/common/NotificationContainer.vue')['default']
    PerformanceMonitor: typeof import('./src/components/common/PerformanceMonitor.vue')['default']
    ProvidersFloating: typeof import('./src/components/ProvidersFloating.vue')['default']
    ResponsiveContainer: typeof import('./src/components/common/ResponsiveContainer.vue')['default']
    ResponsiveGrid: typeof import('./src/components/common/ResponsiveGrid.vue')['default']
    ResponsiveImage: typeof import('./src/components/common/ResponsiveImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StatsFloating: typeof import('./src/components/StatsFloating.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UpdateOverlay: typeof import('./src/components/common/UpdateOverlay.vue')['default']
    UserProfileDialog: typeof import('./src/components/UserProfileDialog.vue')['default']
    WebPreviewDialog: typeof import('./src/components/common/WebPreviewDialog.vue')['default']
    WelcomePage: typeof import('./src/components/WelcomePage.vue')['default']
  }
}
